name: Tauri

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      node-version: 20.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Build
        run: |
          npm ci
          npm run tauri build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src-tauri/target/release/bundle/**/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          promote: true
          body: 'Release ${{ github.ref }}'
